### ISSUE TITLE
Code Navigation

### ISSUE THREAD

**Issue by iRitwik** [SublimeText/CTags#274]
Is there a way to find out all the places where a particular function is being used? 
Right now I have the opposite thing. Given a usage, I can find out the definition but not vice versa. Is there a way to get to a list of all usages in a project from the definition?

**Comment by stephenfin** [comment]
I'm afraid not. I tend to use `Ctrl` + `F` to do this. The issue is that multiple, independent versions of a symbol may exist within a group of files. You'd be able to get a list of all declarations but you couldn't say whether they'd refer to the definition in question. To get this functionality you'd likely need a true IDE
