### ISSUE TITLE
sublime text osx

### ISSUE THREAD

**Issue by benbradford** [SublimeText/CTags#306]
Can someone please explain what this step means:

Alternatively, add the path to the new ctags executable to the settings, under command. If you have Xcode / Apple Developer Tools installed this path will likely be /usr/local/bin/ctags.

Specifically the 'add the path to the new ctags executable to the settings, under command.' what exactly does this mean?

**Comment by adwaitnd** [comment]
Since you mention Apple Dev Tools, I'm assuming you are using an OSX platform.

ctags itself is an seperately installed application to "tag" definitions and variable usages in source code. The default Apple provided version of ctags doesn't work well for the features we need on this sublime plugin. So it is suggested to install your own version of ctags (I used `$ brew install ctags` in the terminal) and add it's path to the plugin by navigating to these menus: *Sublime Text 2*-> *Preferences* -> *Package Settings* -> *CTags* -> *Settings - Default*. Add your ctags path to the `"command":` entry

You can find the path to your ctags application using `$ which ctags` in a terminal (it was `"command": "/usr/local/bin/ctags"` for my system).

**Comment by nicroto** [comment]
It would be awesome to just add this to the description of OS X setup "Alternatively, add it to the package settings under "command" in Sublime Text 2 -> Preferences -> Package Settings -> CTags -> Settings " and you probably want " - User", not " - Default". I also didn't get which settings you meant.

If you have the command line tools of Xcode installed, apparently it uses ctags from /Applications/Xcode/...etc.

Cheers!
